notifications:
  email: false

language: java

jdk:
  - openjdk8
  # - openjdk11

services:
  - docker

env:
  - img=existdb/existdb:latest
  - img=existdb/existdb:release
  - img=existdb/existdb:5.0.0
  - img=existdb/existdb:4.7.1


before_install:
  - docker pull $img
  - docker create  --name exist-ci -p 8080:8080 $img

install:
  - ant

before_script:
  - docker cp ./dist/*.xar exist-ci:exist/autodeploy
  - docker start exist-ci
  # exist needs time
  - sleep 30
  - docker ps

script:
  - ant test
  - xmllint --xpath "//@failures = 0" result/*.xml
  - xmllint --xpath "//@errors = 0" result/*.xml

after_success:
  - docker stop exist-ci
